# docker-compose.yml
version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 8000
    ports:
      - "8000:8000"
    command: npm run dev
    volumes:
      - .:/app/
      - app_node_modules:/app/node_modules

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - app
    ports:
      - "8001:8001"
    volumes:
      - ./frontend:/app/
      - frontend_node_modules:/app/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
  app_node_modules:
  frontend_node_modules:
