version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run prettier:check
  push-to-heroku:
    machine:
      services:
        - docker
    dependencies:
      cache_directories:
        - ~/docker
    commands:
      - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - docker build --rm=false -t registry.heroku.com/thelatintoolkit/web .
      - docker push registry.heroku.com/thelatintoolkit/web:latest
workflows:
    build-test-deploy:
      jobs:
        - build-and-test
        - push-to-heroku:
            requires:
              - build-and-test
            filters:
              branches:
                only:
                  - master
