version: 2.1

orbs:
  docker: circleci/docker@1.0.0
  node: circleci/node@1.1.6

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run prettier:check
  release:
    executor:
      name: docker/machine
    steps:
      - checkout
      - run:
          name: Install Heroku CLI, if necessary
          command: |
            if [[ $(command -v heroku) == "" ]]; then
              curl https://cli-assets.heroku.com/install.sh | sh
            else
              echo "Heroku is already installed. No operation was performed."
            fi
      - run:
          name: Login into Heroku Docker Repository
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - run:
          name: Deploy Heroku Docker Container
          command: |
            heroku container:push web -a $HEROKU_APP_NAME
            heroku container:release web -a $HEROKU_APP_NAME

workflows:
    build-test-deploy:
      jobs:
        - build-and-test
        - approve-release:
            type: approval
            filters:
              branches:
                only:
                  - master
            requires:
              - build-and-test
        - release:
            requires:
              - approve-release
            filters:
              branches:
                only:
                  - master
